### ISSUE TITLE
Change first param of default run script to "./input/complaints.csv"

### ISSUE THREAD

**Issue by ameryisafreeelf** [InsightDataScience/consumer_complaints#3]
Hello,

I think that there's an error in the example script in "run.sh". The script passes in "./inputs/consumer_complaints.csv". However, according to this repo's README, the file that resides in the "inputs" folder should just be called "complaints.csv", not "consumer_complaints.csv". 

I realize this is minor and that the script is meant to just be an example, but I wanted to point it out. If you'd like, I'm happy to make a pull request and make the quick change.

**Comment by emhoa** [comment]
Hi Amery, great catch. Thanks for letting us know. We can update it. Appreciate the heads-up
